#pragma once
#include <iostream>
#include <windows.h>
#include <conio.h>
#include <ctime>
#include <cstdlib>
#include <iomanip>
#include <chrono>
#include <thread>
#include "mapas.h"
#include "Estruturas.h"
#include "funcoesAux.h"
#include "relogio.h"
#include "subirNivel.h"
#include "combate.h";
#include "movimento.h"
#include "Game.h"